version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expense_track
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/expense_track"
    ports:
      - "3001:3000"
    depends_on:
      - db
      - mailcatcher
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: expense_track
      DB_PASSWORD: password
      DB_HOST: db
